.TH "fsinfo" 3 "Tue Nov 2 2021" "motd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fsinfo
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBtotal\fP"
.br
.ti -1c
.RI "double \fBfree\fP"
.br
.ti -1c
.RI "double \fBused\fP"
.br
.ti -1c
.RI "double \fBfree_percent\fP"
.br
.ti -1c
.RI "double \fBused_percent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for motd from the source code\&.
