.TH "src/main.c" 3 "Tue Nov 2 2021" "motd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'motd\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "call the sub-functions and exit "
.ti -1c
.RI "void \fBgreeting\fP (void)"
.br
.RI "prints the datetime and greeting message "
.ti -1c
.RI "void \fBsysinfo\fP (void)"
.br
.RI "prints system informations: kernel, distro, packages number "
.ti -1c
.RI "void \fBfsuse\fP (void)"
.br
.RI "gets and prints filesystem usage "
.ti -1c
.RI "void \fBgoodbye\fP (void)"
.br
.RI "goodbye message: wiki remainder + random quote from fortune "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
lotation (xlapsiu@gmail.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-11-02
.RE
.PP
.SH "LICENSE"
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details at https://www.gnu.org/copyleft/gpl.html
.SH "DESCRIPTION"
.PP
Main file 
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
call the sub-functions and exit 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for motd from the source code\&.
