.TH "md__r_e_a_d_m_e" 3 "Tue Nov 2 2021" "motd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- motd 
Simple message of the day with few informations for arch-based distro
.SH "Dependencies:"
.PP
.IP "\(bu" 2
\fClsb-release\fP (distro and kernel)
.IP "\(bu" 2
\fCfortune-mod\fP (goodbye message)
.IP "\(bu" 2
\fCpacman-contrib\fP (checkupdates script)
.IP "\(bu" 2
\fCcheckupdates-aur\fP (AUR package) 
.PP

